/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * @author Chiquín, Jorge
 * @author Vargas, Alexander
 * @author Bonilla, José
 * @author Fernández, Ysidro
 * @author Rodríguez, Ronald
 */
package Vista;

import lib.Tabla;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JTable;

public class VEdificio extends javax.swing.JDialog {

    /**
     * Creates new form VEdificio1
     */
    public void agregarListener(ActionListener action) {
        this.btnIncluirEm.addActionListener(action);
        this.btnModificarEm.addActionListener(action);
        this.btnEliminarEm.addActionListener(action);
        this.btnLimpiar.addActionListener(action);
        this.btnRegresar.addActionListener(action);
        this.cmbCodigo.addActionListener(action);
        this.cmbCodEd.addActionListener(action);
        
        
    }
    
    public JTable getTablaEdif() {
        return tblEdificio;
    }
    
    public void setValorSpnCantPisos(int valor) {
        spnCantPisos.setValue(valor);
    }
    
    public void setValorSpnCantAp(int valor) {
        spnCantAp.setValue(valor);
    }   
    
    public void setIndexCmbEdificio(int index){
        cmbCodEd.setSelectedIndex(index);
    }
    
    public void selectedCmbEdificio(int index)
    {
        cmbCodEd.setSelectedIndex(index);
    }
    
    public void setTxtIncluirEm(String guardar) {
        this.btnIncluirEm.setText(guardar);
    }
    
    public void vaciarCmbUrbanizaciones() {
        cmbCodigo.removeAllItems();
    }
    
    public void addCmbUrbanizacion(String item) {
        cmbCodigo.addItem(item);
    }
    
    public void vaciarCmdEdificio() {
        cmbCodEd.removeAllItems();
    }
    
    public int getIndexCmbUrbanizacion() {
        return cmbCodigo.getSelectedIndex();
    }
    
    public int getIndexCmbEdificio() {
        return cmbCodEd.getSelectedIndex();
    }
    
    public int getValorSpnCantPisos() {
        return (int) spnCantPisos.getValue();
    }
    
    public int getValorSpnCantAp() {
        return (int) spnCantAp.getValue();
    }
    
    public void addCmbEdificio(String item) {
        cmbCodEd.addItem(item);
    }
    
    public JComboBox<String> getCmbUrbanizacion() {
        return cmbCodigo;
    }
    
    public JComboBox<String> getCmbEdificio() {
        return cmbCodEd;
    }
    
    public String getCmbEdificioSt(){
        return (String) cmbCodEd.getSelectedItem();
    }
    
    public String getCmbUrbaSt(){
        return (String) cmbCodigo.getSelectedItem();
    }
    
    public int getSizeCmbEdificio(){
        return cmbCodEd.getItemCount();
    }
    
    public void enableCmbEdificio(boolean enabled) {
        cmbCodEd.setEnabled(enabled);
    }
    
    public void enableCmbUrba(boolean enabled) {
        cmbCodigo.setEnabled(enabled);
    }
    
    public void setEnabledBtnIncluir(boolean enabled) {
        this.btnIncluirEm.setEnabled(enabled);  
    }
    
    public void setEnabledBtnLimpiar(boolean enabled) {
        this.btnLimpiar.setEnabled(enabled);  
    }
    
    public void enabledBotones(boolean enabled) {
       
        this.btnModificarEm.setEnabled(enabled);
        this.btnEliminarEm.setEnabled(enabled);
        this.btnLimpiar.setEnabled(enabled);
    }
    
    public void enabledSpn(boolean enabled){
        this.spnCantPisos.setEnabled(enabled);
        this.spnCantAp.setEnabled(enabled);
    }
    
    
    public void limpiarCampos(){
        setTxtIncluirEm("Incluir");
        this.cmbCodigo.setEnabled(true);
        this.enableCmbEdificio(false);
        this.cmbCodigo.setSelectedIndex(0); 
        this.spnCantPisos.setValue(1);
        this.spnCantAp.setValue(1);
        this.setEnabledBtnIncluir(false);
        enabledSpn(false);
        enabledBotones(false);
        
        Tabla.vaciarTabla(tblEdificio);
       
    }
   
    
    public VEdificio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIncluirEm = new javax.swing.JButton();
        btnModificarEm = new javax.swing.JButton();
        btnEliminarEm = new javax.swing.JButton();
        spnCantPisos = new javax.swing.JSpinner();
        cmbCodigo = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spnCantAp = new javax.swing.JSpinner();
        cmbCodEd = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEdificio = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edificio");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Edificio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Código de Urbanización");

        jLabel2.setText("Código de Edificio");

        jLabel3.setText("Cantidad de pisos");

        btnIncluirEm.setText("Incluir");

        btnModificarEm.setText("Modificar");

        btnEliminarEm.setText("Eliminar");

        spnCantPisos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        cmbCodigo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnLimpiar.setText("Limpiar");

        jLabel4.setText("Cantidad Aparts.");

        spnCantAp.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        cmbCodEd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIncluirEm)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarEm)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarEm))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spnCantAp, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spnCantPisos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbCodEd, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbCodigo, javax.swing.GroupLayout.Alignment.LEADING, 0, 156, Short.MAX_VALUE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCodEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnCantPisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnCantAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirEm)
                    .addComponent(btnModificarEm)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminarEm))
                .addGap(7, 7, 7))
        );

        tblEdificio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Urb.", "Código Edif.", "Cant. Pisos", "Cant. Aparts."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEdificio);

        btnRegresar.setText("Regresar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegresar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VEdificio dialog = new VEdificio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarEm;
    private javax.swing.JButton btnIncluirEm;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificarEm;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbCodEd;
    private javax.swing.JComboBox<String> cmbCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnCantAp;
    private javax.swing.JSpinner spnCantPisos;
    private javax.swing.JTable tblEdificio;
    // End of variables declaration//GEN-END:variables
}
