/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * @author Chiquín, Jorge
 * @author Vargas, Alexander
 * @author Bonilla, José
 * @author Fernández, Ysidro
 * @author Rodríguez, Ronald
 */
package Vista;

import java.awt.event.ActionListener;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;




public class VMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    public void agregarListener(ActionListener accion) {
        mnuPropietario.addActionListener(accion);
        mnuCalle.addActionListener(accion);
        mnuSalir.addActionListener(accion);
        mnuApartamento.addActionListener(accion);
        mnuCasa.addActionListener(accion);
        mnuEmpresa.addActionListener(accion);
        mnuGastos.addActionListener(accion);
        mnuEdificio.addActionListener(accion);
        mnuCuotas.addActionListener(accion);
        mnuReporteP.addActionListener(accion);
        mnuCuotasUrb.addActionListener(accion);
        mnuPago.addActionListener(accion);
        mnuCuotasDetalladas.addActionListener(accion);
}

    

    
    public VMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        mnbMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuEmpresa = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuCalle = new javax.swing.JMenuItem();
        mnuCasa = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuEdificio = new javax.swing.JMenuItem();
        mnuApartamento = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuPropietario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuCuotas = new javax.swing.JMenuItem();
        mnuGastos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuPago = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuReporteP = new javax.swing.JMenuItem();
        mnuCuotasUrb = new javax.swing.JMenuItem();
        mnuCuotasDetalladas = new javax.swing.JMenuItem();
        mnbSalir = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Condiminio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        jMenu1.setText("Condominios");

        mnuEmpresa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mnuEmpresa.setText("Empresa");
        mnuEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmpresaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEmpresa);
        jMenu1.add(jSeparator1);

        mnuCalle.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuCalle.setText("Calle");
        jMenu1.add(mnuCalle);

        mnuCasa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        mnuCasa.setText("Casa");
        jMenu1.add(mnuCasa);
        jMenu1.add(jSeparator2);

        mnuEdificio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        mnuEdificio.setText("Edificio");
        jMenu1.add(mnuEdificio);

        mnuApartamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        mnuApartamento.setText("Apartamento");
        jMenu1.add(mnuApartamento);
        jMenu1.add(jSeparator3);

        mnuPropietario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mnuPropietario.setText("Propietario");
        jMenu1.add(mnuPropietario);

        jMenu4.setText("Gastos Condominios");

        mnuCuotas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        mnuCuotas.setText("Cuotas");
        jMenu4.add(mnuCuotas);

        mnuGastos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        mnuGastos.setText("Gastos");
        jMenu4.add(mnuGastos);

        jMenu1.add(jMenu4);

        mnbMenu.add(jMenu1);

        jMenu3.setText("Pagos");

        mnuPago.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        mnuPago.setText("Generar Pago");
        jMenu3.add(mnuPago);

        mnbMenu.add(jMenu3);

        jMenu2.setText("Reportes");

        mnuReporteP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        mnuReporteP.setText("Propietarios por Urb");
        mnuReporteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportePActionPerformed(evt);
            }
        });
        jMenu2.add(mnuReporteP);

        mnuCuotasUrb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnuCuotasUrb.setText("Cuotas por Urbanización");
        mnuCuotasUrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCuotasUrbActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCuotasUrb);

        mnuCuotasDetalladas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuCuotasDetalladas.setText("Cuotas detalladas");
        jMenu2.add(mnuCuotasDetalladas);

        mnbMenu.add(jMenu2);

        mnbSalir.setText("Salir");

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mnuSalir.setText("Salir");
        mnbSalir.add(mnuSalir);

        mnbMenu.add(mnbSalir);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuEmpresaActionPerformed

    private void mnuCuotasUrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCuotasUrbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCuotasUrbActionPerformed

    private void mnuReportePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuReportePActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenu mnbSalir;
    private javax.swing.JMenuItem mnuApartamento;
    private javax.swing.JMenuItem mnuCalle;
    private javax.swing.JMenuItem mnuCasa;
    private javax.swing.JMenuItem mnuCuotas;
    private javax.swing.JMenuItem mnuCuotasDetalladas;
    private javax.swing.JMenuItem mnuCuotasUrb;
    private javax.swing.JMenuItem mnuEdificio;
    private javax.swing.JMenuItem mnuEmpresa;
    private javax.swing.JMenuItem mnuGastos;
    private javax.swing.JMenuItem mnuPago;
    private javax.swing.JMenuItem mnuPropietario;
    private javax.swing.JMenuItem mnuReporteP;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables

}
