/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * @author Chiquín, Jorge
 * @author Vargas, Alexander
 * @author Bonilla, José
 * @author Fernández, Ysidro
 * @author Rodríguez, Ronald
 */
package Vista;

import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;


public class VPagos extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    Date now ;
    public VPagos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        now = new java.util.Date(System.currentTimeMillis());//para obtener la fecha del sistema
        SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");  //dar formato a la fecha
        txtFechaEmi.setText(date.format(now)); //carga la fecha en la caja de texto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbCedula = new javax.swing.JComboBox<>();
        cmbVivienda = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbFormapago = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnEfectuar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbPago = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        cmbCodigo = new javax.swing.JComboBox<>();
        cmbCuota = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        txtFechaEmi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pago", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Código Urbanización");

        jLabel2.setText("Cédula Propietario");

        cmbCedula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selccione Propietario" }));
        cmbCedula.setToolTipText("Seleccione Propietario");
        cmbCedula.setName("cmbCedula"); // NOI18N

        cmbVivienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Código de Viivienda" }));

        jLabel3.setText("Vivienda");

        jLabel4.setText("Forma de pago");

        cmbFormapago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Forma de Pago" }));

        jLabel5.setText("Fecha emisión");

        jLabel6.setText("Monto");

        txtMonto.setEditable(false);

        jLabel7.setText("Bs.");

        btnEfectuar.setText("Generar");

        btnEliminar.setText("Eliminar");

        btnCancelar.setText("Cancelar");

        jLabel8.setText("Código Pago");

        cmbPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Código Pago" }));
        cmbPago.setToolTipText("");
        cmbPago.setName("cmbCodPago"); // NOI18N

        btnBuscar.setText("Buscar");

        cmbCodigo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCodigo.setName("cmbCodigo"); // NOI18N
        cmbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCodigoActionPerformed(evt);
            }
        });

        cmbCuota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Cuota" }));

        jLabel9.setText("Cuota");

        btnRegresar.setText("Regresar");

        txtFechaEmi.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbPago, 0, 186, Short.MAX_VALUE)
                                .addComponent(cmbCodigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbCedula, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbVivienda, javax.swing.GroupLayout.Alignment.LEADING, 0, 186, Short.MAX_VALUE)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbCuota, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbFormapago, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel7))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(btnEfectuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFechaEmi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscar)
                    .addComponent(cmbCodigo))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEfectuar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbFormapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFechaEmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminar)
                    .addComponent(btnRegresar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VPagos dialog = new VPagos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
     public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnEfectuar() {
        return btnEfectuar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JComboBox<String> getCmbCedula() {
        return cmbCedula;
    }

    public JComboBox<String> getCmbCodigo() {
        return cmbCodigo;
    }
     public JComboBox<String> getCmbPago() {
        return cmbPago;
    }

    public JComboBox<String> getCmbCuota() {
        return cmbCuota;
    }

    public JComboBox<String> getCmbFormapago() {
        return cmbFormapago;
    }

    public JComboBox<String> getCmbUrbanizacion() {
        return cmbCodigo;
    }

    public JComboBox<String> getCmbVivienda() {
        return cmbVivienda;
    }
     public void vaciarCmbUrbanizaciones() {
        cmbCodigo.removeAllItems();
    }
     
      public void addCmbUrbanizacion(String item) {
        cmbCodigo.addItem(item);
    }
    
     
     public int getIndexCmbUrbanizacion() {
        return cmbCodigo.getSelectedIndex();
    }
     public int getIndexCmbCuota() {
        return cmbCuota.getSelectedIndex();
    }
     public String getCmbUrbaSt(){
        return (String) cmbCodigo.getSelectedItem();
    }
      public void setIndexCmbUrbanizacion(int index){
        cmbCodigo.setSelectedIndex(index);
    }
      public void addCmbPagos(String item) {
     cmbPago.addItem(item);
    }
      
        public void setIndexCmbPagos(int index) {
        
             cmbPago.setSelectedIndex(index);
    }

    public void selectedCmbPagos(int index) {
         cmbPago.setSelectedIndex(index);
    }
     public void vaciarCmdPago() {
      cmbPago.removeAllItems();
    }
     public void vaciarCmdFormaPago() {
      cmbFormapago.removeAllItems();
    }
      public void addCmbPago(String item) {
        cmbPago.addItem(item);
    }
     public void addCmbCuota(String item) {
        cmbCuota.addItem(item);
    } 
      public void addCmbFormaPago(String item) {
        cmbFormapago.addItem(item);
    }
    public void enableCmbPago(boolean enabled) {
        cmbPago.setEnabled(enabled);
    }

  public void setEnabledBtnEfectuar(boolean b) {
     btnEfectuar.setEnabled(b);
    }
  
   public void setEnabledBtnCancelar(boolean b) {
        btnCancelar.setEnabled(b);
    }
   public void setEnabledBtnBuscar(boolean b) {
        btnBuscar.setEnabled(b);
    }
    public int getIndexCmbPagos() {
         return cmbPago.getSelectedIndex();
    }
    public int getIndexCmbCedula() {
         return cmbCedula.getSelectedIndex();
    }
    public int getIndexCmbVivienda() {
         return cmbVivienda.getSelectedIndex();
    }

    public int getIndexCmbFormaPago() {
         return cmbFormapago.getSelectedIndex();
    }
    
    public void enableCmbUrba(boolean b) {
        cmbCodigo.setEnabled(b);
    }
    
    public void enabledBotones(boolean enabled) {
       
        this.btnBuscar.setEnabled(enabled);
        this.btnCancelar.setEnabled(enabled);
        this.btnEfectuar.setEnabled(enabled);
         this.btnEliminar.setEnabled(enabled);
    }
    
      public void limpiarCampos() {
       
        this.cmbCodigo.setEnabled(true);
        this.enableCmbPago(false);
        this.enableCmbCedula(false);
        this.enableCmbVivienda(false);
        this.enableCmbCuota(false);
        this.enableCmbFormaPago(false);
        this.cmbCodigo.setSelectedIndex(0);
        this.cmbCedula.setSelectedIndex(0);
        this.cmbCuota.setSelectedIndex(0);
        this.cmbFormapago.setSelectedIndex(0);
        this.setEnabledBtnEfectuar(false);
        enabledBotones(false);
        btnEfectuar.setText("Generar");
        
    }
    public String getCmbPagoSt(){
        return (String) cmbPago.getSelectedItem();
    }
    public float getTxtMonto(){
        return Float.parseFloat(txtMonto.getText());
    }
    public Date getTxtFecha(){
        
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");  //dar formato a la fecha
        String fecha = date.format(now);
        Date f =  java.sql.Date.valueOf(fecha);
        return f;
    }
    public String getCmbCedulaSt(){
        return (String) cmbCedula.getSelectedItem();
    }
    public String getCmbCuotaSt(){
        return (String) cmbCuota.getSelectedItem();
    }
    public String getCmbViviendaSt(){
        return (String) cmbVivienda.getSelectedItem();
    }
    public void setValorCmbPropietario(String valor) {
        cmbCedula.setSelectedItem(valor);

    }

    public void setValorCmbVivienda(String valor) {
        cmbVivienda.setSelectedItem(valor);

    }

    public void setValorCmbCuota(double valor) {
        cmbCuota.setSelectedItem(valor);

    }
    public void setTxtBtnEfectuar(String modificar) {
        btnEfectuar.setText(modificar);
    }
     public void setTxtMonto(String modificar) {
        txtMonto.setText(modificar);
    }
    public void setValorCmbPago(String valor) {
        cmbPago.setSelectedItem(valor);
    }
    public void agregarListener(ActionListener action) {
        this.btnBuscar.addActionListener(action);
        this.btnEfectuar.addActionListener(action);
        this.btnEliminar.addActionListener(action);
        this.btnCancelar.addActionListener(action);
        this.cmbCodigo.addActionListener(action);
        this.cmbPago.addActionListener(action);
        this.cmbCedula.addActionListener(action);
        this.cmbCuota.addActionListener(action);
        this.cmbFormapago.addActionListener(action);
        this.cmbVivienda.addActionListener(action);
        
} 

 public void enableCmbVivienda(boolean b)
 {
  cmbVivienda.setEnabled(b);
 }

 public void enableCmbCedula(boolean b) {
        cmbCedula.setEnabled(b);
    }
 
  public void enableCmbCuota(boolean b) {
     cmbCuota.setEnabled(b);
    }
  public void enableCmbFormaPago(boolean b) {
     cmbFormapago.setEnabled(b);
    }
   public void vaciarCmbCedula() {
        cmbCedula.removeAllItems(); 
    }

    public void vaciarCmbCuota()
    {
    cmbCuota.removeAllItems();
    }
     public void enableBtnEfectuar(boolean b) 
     {
         btnEfectuar.setEnabled(b);
     }
     public void vaciarCmbVivienda() {
        cmbVivienda.removeAllItems();
        cmbVivienda.addItem("Seleccione Vivienda");
    }   
         
     public void addCmbCedula(String cedula) {
         cmbCedula.addItem(cedula);
    }
     public void addCmbVivienda(String cedula) {
         cmbVivienda.addItem(cedula);
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEfectuar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbCedula;
    private javax.swing.JComboBox<String> cmbCodigo;
    private javax.swing.JComboBox<String> cmbCuota;
    private javax.swing.JComboBox<String> cmbFormapago;
    private javax.swing.JComboBox<String> cmbPago;
    private javax.swing.JComboBox<String> cmbVivienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFechaEmi;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables

    
}
